Repository wecode-bootcamp-korea/26-2nd-Weterest-frontend, pull requests merged in 2021-11, with the labels that each got.

#3 [26기 임연수]Add: 메인화면 레이아웃 구현
  .gitignore
  public/data/hi.md
  public/data/main/mainMockUp.json
  public/images/hi.md
  public/images/image_a1.jpeg
  public/images/image_a10.jpeg
  public/images/image_a11.jpeg
  public/images/image_a12.jpeg
  public/images/image_a13.jpeg
  public/images/image_a2.jpeg
  public/images/image_a3.jpeg
  public/images/image_a4.jpeg
  public/images/image_a5.jpeg
  public/images/image_a6.jpeg
  public/images/image_a7.jpeg
  public/images/image_a8.jpeg
  public/images/image_a9.jpeg
  src/components/WeterestGrid/GridInner.js
  src/components/WeterestGrid/GridPost.js
  src/components/WeterestGrid/WeterestGrid.js
  src/pages/Main/Main.js
  src/styles/GlobalStyle.js
  src/styles/StyleData.js
Labels: Status: 리뷰 요청

#2 [26기 김유신] Reflector: 리뷰 반영 및 z-index 수정
  package-lock.json
  package.json
  src/components/Nav/Nav.js
Labels: Status: 추가 기능 구현중

#4 [26기 김유신] Add: upload 페이지 레이아웃 완성 및 통신준비 완료
  src/pages/Upload/Upload.js
Labels: Status: 수정 요청

#6 [26기 임연수] Add: 디테일 페이지 페이지 구현
  package-lock.json
  public/data/main/detailMockUp.json
  public/images/image_a14.jpeg
  src/Config.js
  src/components/SavePinIcon.js
  src/components/WeterestGrid/WeterestGrid.js
  src/pages/Detail/Detail.js
  src/pages/Detail/PinDetail/DetailComment/CommentComps/CommentFirstMent.js
  src/pages/Detail/PinDetail/DetailComment/CommentComps/CommentItem.js
  src/pages/Detail/PinDetail/DetailComment/CommentComps/DetailCommentList.js
  src/pages/Detail/PinDetail/DetailComment/CommentComps/UserProfileCircle.js
  src/pages/Detail/PinDetail/DetailComment/DetailComment.js
  src/pages/Detail/PinDetail/DetailFeaturedUser.js
  src/pages/Detail/PinDetail/PinDetail.js
  src/pages/Main/Main.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#7 [26기 임연수] Refactor: 매직 그리드 컴포넌트 개선
  public/data/main/mainMockUp.json
  public/data/mockUp/detail.json
  public/data/mockUp/main.json
  public/data/mockUp/myPage.json
  public/data/mockUp/search.json
  src/Config.js
  src/Routers.js
  src/components/Icons/MoreAndShareIcons.js
  src/components/Icons/SavePinIcon.js
  src/components/WeterestGrid/GridInner.js
  src/components/WeterestGrid/GridPost.js
  src/components/WeterestGrid/GridPost/GridPost.js
  src/components/WeterestGrid/WeterestGrid.js
  src/components/fetch/FetchInform.js
  src/components/fetch/useScrollFetch.js
  src/pages/Detail/Detail.js
  src/pages/Detail/PinDetail/DetailFeaturedUser.js
  src/pages/Detail/PinDetail/PinDetail.js
  src/pages/Main/Main.js
  src/pages/SearchPage/SearchPage.js
  src/styles/StyleData.js
Labels: Status: 리뷰 요청

#1 [26기 전창민] Add: 스크롤 이벤트 구현
  .gitignore
  public/data/enterimages.json
  public/images/downbutton.png
  public/images/enterimage/barcelona.jpeg
  public/images/enterimage/bluesea.jpeg
  public/images/enterimage/cake.jpeg
  public/images/enterimage/cat.jpeg
  public/images/enterimage/cat2.jpeg
  public/images/enterimage/curbby.jpeg
  public/images/enterimage/franceload.png
  public/images/enterimage/italy.png
  public/images/enterimage/joker.png
  public/images/enterimage/load.jpeg
  public/images/enterimage/matrix.jpeg
  public/images/enterimage/movieposter.jpeg
  public/images/enterimage/pari.jpeg
  public/images/enterimage/pari2.jpeg
  public/images/enterimage/redsea.jpeg
  public/images/enterimage/seoul.jpeg
  public/images/enterimage/shiba.jpeg
  public/images/enterimage/spain.jpeg
  public/images/enterimage/thunder.jpeg
  public/images/enterimage/thunder2.jpeg
  public/images/kakaobutton 2.png
  public/images/kakaobutton.png
  public/images/upbutton.png
  public/images/xbutton.jpeg
  public/index.html
  src/Config.js
  src/Routers.js
  src/User.js
  src/pages/Login/Circle.js
  src/pages/Login/CircleSvg.svg
  src/pages/Login/EntryPage.js
  src/pages/Login/ImagesContainer.js
  src/pages/Login/KakaoLogin.js
  src/pages/Login/Login.js
  src/pages/Login/LoginIntroduce.js
  src/pages/Login/LoginModal.js
  src/pages/Login/OAuth.js
  src/pages/Upload/Upload.js
Labels: Status: 리뷰 요청

#13 [26기 김유신] add: 로그아웃 기능 구현완료
  src/components/Nav/Nav.js
Labels: Status: Conflict 해결 요청

#14 [26기 임연수]Refactor: 2차 배포를 위한 마무리 코드개선 및 정리
  src/components/Grids/GridPost/IntroPost.js
  src/components/Grids/MyImageGrid.js
  src/components/Grids/PinnedBoardGrid.js
  src/components/Nav/Nav.js
  src/components/SavePinIcon.js
  src/components/fetch/useMyImageFetch.js
  src/components/fetch/usePinnedBoardFetch.js
  src/pages/Login/LoginIntroduce.js
  src/pages/MyPage/MyPage.js
  src/pages/Upload/Upload.js
Labels: Status: 추가 기능 구현중

#15 [26기 임연수] Add: 윈터레스트 로고
  src/components/Nav/Nav.js
  src/pages/Login/EntryPage.js
  src/pages/Login/LoginModal.js
Labels: Status: 리뷰 요청
